# Generated by Django 5.2 on 2025-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='about',
            field=models.CharField(blank=True, choices=[('feature', 'Feature'), ('user', 'User'), ('product', 'Product'), ('bug_report', 'Bug Report')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('complaint', 'Complaint'), ('improvement', 'Improvement')], max_length=20, null=True),
        ),
    ]
