# Generated by Django 5.2 on 2025-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_feedback_about_feedback_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='to_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
