# Generated by Django 5.2 on 2025-09-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=tuple),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
